model_name: "llama2-chat"
# model_weights: "/data/shared/llama2/llama-2-7b-chat-weights/"
model_weights: "/gpfs/data/superlab/models/llama2/llama/checkpoints/hf/Llama-2-7b-chat-hf"
task: "open_qa"
max_new_tokens: 50
# max_new_tokens: 4096
model_args:
  device_map: "auto"
tokenizer_args:
  # add_eos_token: true  # for fine-tuning
  padding_side: 'left'